apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-well-known-files
  namespace: "{{ .Release.Namespace }}"
data:
  ca-install-trust.sh:
{{ ( .Files.Get "files/ca-install-trust.sh" ) | toYaml | indent 4 }}
  default.conf:
{{ ( .Files.Get "files/default.conf" ) | toYaml | indent 4 }}
  ca-trust.txt: |
    # To install the cluster certificates into your system, use the command below:
    curl -kL http://{{ .Values.cluster.hostname }}/.well-known/pki-validation/ca-install-trust.sh | bash -s http://{{ .Values.cluster.hostname }}/.well-known/pki-validation/ca.pem
