apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: registry-certificate-tls

  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "{{ .Values.hostname }}"
    - "*.{{ .Values.hostname }}"

  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
