apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: cluster-docker-registry-pull
  namespace: "{{ .Release.Namespace }}"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "{{ .Values.hostname }}:{{ .Values.port }}": {
                "username": "{{ .Values.auth.username }}",
                "password": "{{ .Values.auth.password }}",
                "auth": "{{ (printf "%s:%s" .Values.auth.username .Values.auth.password) | b64enc }}"
            }
        }
    }
  DOCKER_PASSWORD: "{{ .Values.auth.password }}"
  DOCKER_USERNAME: "{{ .Values.auth.username }}"
  DOCKER_REGISTRY_URL: "{{ .Values.hostname }}:{{ .Values.port }}"
