apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-registry-auth
  namespace: "{{ .Release.Namespace }}"
stringData:
  htpasswd: "{{ htpasswd .Values.auth.username .Values.auth.password }}"
  token.secret: "{{ .Values.secret }}"
