---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data
  labels:
    app: docker-registry
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
