---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: registry
      protocol: TCP
      port: {{ .Values.port }}
      nodePort: {{ .Values.port }}
      targetPort: registry
